import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/src/context/CartContext";
// 1. Κάνουμε import το νέο μας Header
import Header from "@/src/components/Header"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      {/* Προσθέσαμε το bg-gray-50 και text-gray-900 εδώ! */}
      <body className={`${geistSans.variable} ${geistMono.variable} min-h-full flex flex-col h-full antialiased bg-gray-50 text-gray-900`}>
        <CartProvider>
          {/* 2. Το Header μπαίνει ψηλά για να εμφανίζεται σε όλες τις σελίδες */}
          <Header />

          {/* Αφαιρέσαμε το style={{ padding: '2rem' }} για να απλώνει σωστά η σελίδα! */}
          <main className="flex-1 flex flex-col">
            {children}
          </main>
        </CartProvider>
      </body>
    </html>
  );
}